#%%
# set the system path to include the parent directory
import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))
import pandas as pd
import os
import numpy as np
from generation_utils import fix_wsl_paths
import json
from tqdm import tqdm
import atexit
from concurrent.futures import ThreadPoolExecutor, as_completed
import threading


""" Lets do a script to aggregate the required data for the json dataset for fine-tuning LLava on generated gaze-following data.
1. Use the results csv generated by gaze_follow_ds.py to get the person description index
2. Use the person description index and extract the full description from person_description_text_data.json of every generated (from llava_extract_ppl_loc_and_gaze.py) dir
 result in  eg 00000003_attn\layer_23
3. Use the steered attention generated description of the target gaze point (generated from extract_attention_interactive_refactored.py script) and extracti the full description from eg "batch_bias_sweep_results_20250828_053454.json" files
4. Split the full description into source (person description) and target (gaze point description)
5. For every image in the generated dir from 3., create a json entry with the image path, source and target description, prefering person description from 2. if available, otherwise using the one from 3.
"""



#%% Relevant paths
steered_generated_results = r"D:\Projects\data\gazefollow\results\steered_attention_runs\refactored_experiment_20250825_232643\batch_bias_sweep_results_20250828_053454.json"
gazefollowing_results_csv = r"D:\Projects\data\gazefollow\results\valid_runs\20250902_015248_You_are_an_expert_vision_assis_results.csv"
person_description_data_dir = r"D:\Projects\data\gazefollow\results\valid_runs\20250902_015248_00000001_00030291"

steered_generated_results = fix_wsl_paths(steered_generated_results)
gazefollowing_results_csv = fix_wsl_paths(gazefollowing_results_csv)
person_description_data_dir = fix_wsl_paths(person_description_data_dir)

#%% Load the results csv
gazefollowing_results_df = pd.read_csv(gazefollowing_results_csv)
steered_results_df = pd.read_json(steered_generated_results).T
# change the index to be the image name (zfilled to 8 digits)
steered_results_df.index = steered_results_df.index.astype(str).str.zfill(8)
# set the index of gazefollowing results to be the image name using 'image_path' column
gazefollowing_results_df.index = gazefollowing_results_df["image_path"].str.split("/").str[-1].str.split(".").str[0]
# %% Steered results process: split to source and target description based on the first occurrence of "looking at"
steered_results_df["source_description"] = steered_results_df["generated_prompt"].str.split("looking at").str[0]
steered_results_df["target_description"] = steered_results_df["generated_prompt"].str.split("looking at").str[1]

#%% Load all the description files
desc_data = {}
def load_description_file(image_id, person_description_data_dir):
    """Load a single description file for given image_id"""
    desc_file_path = Path(person_description_data_dir) / f"{image_id}_attn" / "layer_23" / "person_description_text_data.json"
    if not desc_file_path.exists():
        return image_id, None
    
    try:
        with open(desc_file_path, "r") as f:
            image_desc = json.load(f)
        return image_id, image_desc
    except Exception as e:
        print(f"Error loading {desc_file_path}: {e}")
        return image_id, None

def load_all_description_files(gazefollowing_results_df, person_description_data_dir, max_workers=8):
    """Load all description files in parallel and return a dict of image_id -> description data."""
    desc_data = {}
    desc_data_lock = threading.Lock()
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        future_to_image_id = {
            executor.submit(load_description_file, row.name, person_description_data_dir): row.name
            for _, row in gazefollowing_results_df.iterrows()
        }
        for future in tqdm(as_completed(future_to_image_id), total=len(future_to_image_id), desc="Loading description files"):
            image_id, image_desc = future.result()
            if image_desc is not None:
                with desc_data_lock:
                    desc_data[image_id] = image_desc
            else:
                print(f"Description file for {image_id} does not exist, skipping.")
    return desc_data

# Example usage:
desc_data = load_all_description_files(gazefollowing_results_df, person_description_data_dir)

#%%
ind = 0
global missed_summary
missed_summary = {
    'not_in_gazefollowing': set(),
    'not_in_steered': set(),
    'nan_index': set(),
    'index_out_of_range': set()
}
def _print_missed_summary():
    s = globals()['missed_summary']
    total_unique = len(set().union(*s.values()))
    print("Missed summary:")
    for k, v in s.items():
        print(f"  {k}: {len(v)}")
    print(f"  total_unique_missed: {total_unique}")
atexit.register(_print_missed_summary)

periodic_save_every = 5000  # Save every N iterations
periodic_save_path = os.path.join(os.path.dirname(gazefollowing_results_csv), "gazefollowing_results_periodic.csv")

for image_id, row in tqdm(gazefollowing_results_df.iterrows(), total=len(gazefollowing_results_df), desc="Processing gazefollowing results"):
    if image_id not in gazefollowing_results_df.index:
        print(f"Image id {image_id} not found in gazefollowing results, skipping.")
        missed_summary['not_in_gazefollowing'].add(image_id)
        continue

    result_row = gazefollowing_results_df.loc[image_id]
    person_desc_index = result_row["llava_matched_person_id"] - 1 # convert to 0-based index
    if np.isnan(person_desc_index):
        print(f"Person description index for image id {image_id} is NaN, skipping.")
        missed_summary['nan_index'].add(image_id)
        continue

    person_desc_index = int(person_desc_index)
    img_desc_data = desc_data.get(image_id, None)
    if img_desc_data is None:
        print(f"Description data for image id {image_id} not found, skipping.")
        missed_summary['not_in_steered'].add(image_id)
        continue

    if len(img_desc_data["person_descriptions"]) <= person_desc_index:
        print(f"Person description index {person_desc_index} out of range for image id {image_id}, skipping.")
        missed_summary['index_out_of_range'].add(image_id)
        continue

    full_person_desc = img_desc_data["person_descriptions"][person_desc_index]
    # split the full_person_desc into source and target based on the first occurrence of "looking at"
    if "looking at" in full_person_desc:
        source_desc = full_person_desc.split("looking at")[0]
        target_desc = full_person_desc.split("looking at")[1]
        gazefollowing_results_df.at[image_id, "source_description"] = source_desc
        gazefollowing_results_df.at[image_id, "target_description"] = target_desc

    gazefollowing_results_df.at[image_id, "full_description"] = full_person_desc
    ind += 1

    # Periodic saving
    if ind % periodic_save_every == 0:
        gazefollowing_results_df.to_csv(periodic_save_path, index=False)
        print(f"Periodic save at iteration {ind} to {periodic_save_path}")

    # if ind >= 100:     # testing
    #     break   
gazefollowing_results_df.to_csv(periodic_save_path, index=False)
print(f"Final save to {periodic_save_path}")

# %% Lets combine the dataframes, prefering the gazefollowing_results_df person descriptions if available
# join on the index (image id)
gazefollowing_results_df = pd.read_csv(periodic_save_path, index_col=0)
gazefollowing_results_df.index = gazefollowing_results_df['image_path'].str.split("/").str[-1].str.split(".").str[0]
steered_prefixed = steered_results_df[["source_description", "target_description"]].add_prefix("steered_")
combined_df = gazefollowing_results_df.join(steered_prefixed)

# %% Save the results to a csv
output_csv_path = os.path.join(os.path.dirname(gazefollowing_results_csv), "combined_description_results.csv")
combined_df.to_csv(output_csv_path, index=True)
print(f"Combined results saved to {output_csv_path}")

# %%
